language: python
install: pip install tox-travis
script: tox
stages:
  - name: test
  - name: build
    if: type = push AND tag is present
jobs:
  include:
    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
    - stage: test
      python: 3.8
    - stage: build
      name: 'PyPI upload'
      python: 3.7
      deploy:
        provider: pypi
        user: DeanWay
        password:
          secure: BVWvSpp1iqY1h75QqQYzNsQGBbVYE0dllt7NaAWiV3S3FjQmtO8FdxI9krZS5j3BwlrLNAbu6yeSCiRadp7kC3O4aLNBkCjLLOEL1NlJSgNOzLBolnrnxs2HCEdggJZH7qsZSNDC5H+HGOJ+UQ5Ts+FcKPMzuJlA/QfkW+OB5xjjrfRLcrKPoiyOVHaWOQg0iK2aeJDHYzClo387GfFLG4OANbMEbXQa3xlemB5dw5G7m1HFNoqjnIm0EwwHl5GetNcY2/+cMlFWdKRE725mAEtqjwnnTKzZ9jocDZcOim07568jjR4uPY0SlPZ+nF2LW3VD4mUvUMYgh2piQRnoZQSy+Hp70drxslyLmaS3vzIQXeCJYQg3R7HtFr8oKf/h2Z+FLpCylrHDcpaBY8UTr+/1KUY4N2qoGx6c0ATw9gVtUUYJrlQPIGhlF7vCPYqs5kIsnxlBcup2o1H5HMG8kM5PYYNtPzNk+s91sLoCOfwksQCSn59FFWmn94lbdo8urb7xZrwodiXeH1Lo3Sk/5wVVu2hS0qwNPWqMXLsZ91pdLn6+oj/s+bUvS+UN7KG4YvSBfEo/CWF3OE1FXmUrTdeqDJGJBKIooEwiYiwZvTVNdbm8uyVN9yeecnQ/rntV4c2e4wS1eyP6XI7RiNPeqPkinz63+yt37e1D3FCnLrs=
        on:
          tags: true
